name: get gsm secrets

on:
  workflow_dispatch

jobs:
  secret:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.google_credentials }}
      - id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v3'
        with:
          secrets: |-
            token:ardent-case-465107-c9/AnupTestSecret
          export_to_environment: true
      - id: 'publish'
        run: |
          echo '${{ env.token }}'
